/* =========================================================
   英語習熟トレーナー  カリキュラム＆問題データ
   区分（小学生 / 中学生 / 高校生）→ 学習単元 → 講義・演習
   各単元は「診断 → 講義 → 演習」で習熟を進める構成。
   問題形式: choice(選択) / order(並べ替え) / input(入力) / pos(品詞識別)
   ========================================================= */

const CURRICULUM = [
  /* ===================== 小学生 ===================== */
  {
    id: "elementary",
    stage: "小学生",
    color: "#3b9c5a",
    desc: "英語の音・文字・基本の型に親しみ、中学英語の土台をつくる区分。",
    units: [
      {
        id: "el-phonics",
        title: "アルファベットとフォニックス",
        goal: "26文字の名前読みと音読み（フォニックス）を結びつけ、ローマ字と英語の違いをつかむ。",
        diagnosis: "アルファベットを大文字・小文字で書け、a/e/i/o/u の音が言えますか？",
        lecture: [
          { h: "名前読みと音読み", body: "文字には『名前』（A=エイ）と『音』（a=ア／ェァ）がある。読みは音読みを使う。" },
          { h: "母音の基本音", body: "a=ア, e=エ, i=イ, o=オ, u=ア の短い音。cat, pen, sit, dog, cup で確認。" },
          { h: "ローマ字と英語は別物", body: "ローマ字の『ka・ki・ku』と英語の発音はちがう。英語は音のかたまりで読む。" },
          { h: "サイレントe", body: "語尾の e は読まず、前の母音を名前読みに変える。cap→cape, kit→kite。" },
        ],
        exercises: [
          { type: "choice", q: "「cat」の最初の音 c はどれに近い？", choices: ["ク", "ス", "チ", "シュ"], answer: 0, explain: "c は多くの場合『ク』の音。cat=キャット。" },
          { type: "choice", q: "サイレントe のはたらきとして正しいものは？", choices: ["e を強く読む", "前の母音を名前読みにする", "語頭の音を消す", "意味を否定にする"], answer: 1, explain: "kit（キット）→ kite（カイト）のように前の母音が名前読みになる。" },
          { type: "input", q: "「犬」を表す3文字の英単語をローマ字でなく英語のつづりで書こう。", answers: ["dog", "Dog"], explain: "d-o-g。o は短く『オ』。" },
          { type: "pos", sentence: "I have a red ball.", target: "red", choices: ["名詞", "動詞", "形容詞", "前置詞"], answer: 2, explain: "red（赤い）は ball を説明する形容詞。" },
        ],
      },
      {
        id: "el-words",
        title: "身の回りの基本単語",
        goal: "数・色・曜日・家族・食べ物など、身の回りの名詞・動詞・形容詞を増やす。",
        diagnosis: "色や曜日、家族を表す英単語をいくつ言えますか？",
        lecture: [
          { h: "分野でまとめて覚える", body: "色（red/blue/green）、曜日（Monday…）、家族（father/mother/brother）など仲間でまとめる。" },
          { h: "基本動詞", body: "like / have / go / play / eat / see など日常の動作を表す語を覚える。" },
          { h: "対になる形容詞", body: "big↔small, hot↔cold, happy↔sad のようにセットで覚えると定着しやすい。" },
        ],
        exercises: [
          { type: "choice", q: "「Wednesday」は何曜日？", choices: ["火曜日", "水曜日", "木曜日", "金曜日"], answer: 1, explain: "Wednesday＝水曜日。発音は『ウェンズデイ』。" },
          { type: "choice", q: "「small」の反対の意味の語は？", choices: ["short", "big", "long", "tall"], answer: 1, explain: "small（小さい）↔ big（大きい）。" },
          { type: "input", q: "「青」を表す英単語を書こう。", answers: ["blue", "Blue"], explain: "blue＝青。" },
          { type: "pos", sentence: "We play soccer.", target: "play", choices: ["名詞", "動詞", "形容詞", "副詞"], answer: 1, explain: "play（〜をする）は動作を表す動詞。" },
        ],
      },
      {
        id: "el-be",
        title: "be動詞の文（This is / I am）",
        goal: "am / is / are の使い分けと、『〜です』の文の型をつかむ。",
        diagnosis: "I ___ a student. の空所に入る語が分かりますか？",
        lecture: [
          { h: "主語で形が変わる", body: "I→am, you/複数→are, he/she/it・単数→is。" },
          { h: "be動詞の意味", body: "『〜です』『〜にいる/ある』を表す。This is a pen.／I am happy." },
          { h: "否定はnotを後ろに", body: "is not / are not / am not。短縮は isn't / aren't。" },
        ],
        exercises: [
          { type: "choice", q: "「She ___ my friend.」の空所に入る語は？", choices: ["am", "is", "are", "be"], answer: 1, explain: "主語 She は3人称単数なので is。" },
          { type: "order", q: "日本語「これはノートです。」を英語に並べ替えよう。", tokens: ["is", "This", "a", "notebook"], answer: ["This", "is", "a", "notebook"], explain: "This is a notebook. 主語＋be動詞＋名詞。" },
          { type: "input", q: "「I ___ from Japan.」の空所に入るbe動詞を書こう。", answers: ["am"], explain: "主語が I のときは am。" },
          { type: "choice", q: "「You are not late.」の意味は？", choices: ["あなたは遅れています", "あなたは遅れていません", "あなたは遅れますか", "遅れないで"], answer: 1, explain: "are not で否定。『遅れていない』。" },
        ],
      },
      {
        id: "el-verb",
        title: "一般動詞の文（I like / I play）",
        goal: "be動詞以外の動詞（一般動詞）を使って『〜する』の文をつくる。",
        diagnosis: "I play tennis. の play のような語を一般動詞と呼ぶと知っていますか？",
        lecture: [
          { h: "一般動詞とは", body: "like, play, have, go など動作・状態を表す動詞。be動詞とは別物。" },
          { h: "文の型", body: "主語＋一般動詞＋目的語。I like music.／We play soccer." },
          { h: "be動詞と混ぜない", body: "× I am play tennis. ○ I play tennis. be動詞と一般動詞は同時に使わない。" },
        ],
        exercises: [
          { type: "choice", q: "正しい文はどれ？", choices: ["I am like dogs.", "I like dogs.", "I am dogs like.", "I likes dogs."], answer: 1, explain: "一般動詞 like を使うので am は不要。主語 I に s も付けない。" },
          { type: "order", q: "日本語「私は毎日英語を勉強します。」を並べ替えよう。", tokens: ["study", "I", "every day", "English"], answer: ["I", "study", "English", "every day"], explain: "I study English every day." },
          { type: "input", q: "「私は音楽が好きです。」を英語で書こう（3語）。", answers: ["I like music", "I like music."], explain: "I like music. 一般動詞 like の文。" },
          { type: "pos", sentence: "They go to school.", target: "to", choices: ["動詞", "名詞", "前置詞", "形容詞"], answer: 2, explain: "to は方向を表す前置詞。" },
        ],
      },
      {
        id: "el-question",
        title: "疑問文と答え方（Do you ~? / Can you ~?）",
        goal: "一般動詞の疑問文・否定文と、Yes/Noの答え方をつかむ。",
        diagnosis: "「あなたはサッカーをしますか」を英語で言えますか？",
        lecture: [
          { h: "一般動詞の疑問文", body: "文の先頭に Do を置く。Do you play soccer? 答えは Yes, I do. / No, I don't." },
          { h: "否定文", body: "動詞の前に don't を置く。I don't like natto." },
          { h: "canの疑問文", body: "Can you swim? — Yes, I can. / No, I can't." },
        ],
        exercises: [
          { type: "choice", q: "「Do you like apples?」への正しい答えは？", choices: ["Yes, I am.", "Yes, I do.", "Yes, I like.", "Yes, you do."], answer: 1, explain: "Do の疑問文には do で答える。Yes, I do." },
          { type: "order", q: "「あなたはピアノをひけますか。」を並べ替えよう。", tokens: ["you", "play", "Can", "the piano"], answer: ["Can", "you", "play", "the piano"], explain: "Can you play the piano?" },
          { type: "input", q: "「私は納豆が好きではありません。」の空所:「I ___ like natto.」", answers: ["don't", "do not"], explain: "一般動詞の否定は don't（do not）を動詞の前に。" },
          { type: "choice", q: "「Can you swim?」の意味は？", choices: ["泳ぎますか", "泳げますか", "泳ぎたいですか", "泳ぎました"], answer: 1, explain: "can は『〜できる』。『泳げますか』。" },
        ],
      },
      {
        id: "el-greeting",
        title: "あいさつと自己紹介",
        goal: "あいさつ表現と自己紹介の定型文を、使える形で身につける。",
        diagnosis: "英語で名前・好きなもの・できることを言えますか？",
        lecture: [
          { h: "あいさつ", body: "Hello. / How are you? — I'm fine, thank you. / See you." },
          { h: "自己紹介の型", body: "My name is ~. / I'm from ~. / I like ~. / I can ~." },
          { h: "相手にたずねる", body: "What's your name? / What do you like? でやり取りを広げる。" },
        ],
        exercises: [
          { type: "choice", q: "「How are you?」への自然な返事は？", choices: ["My name is Ken.", "I'm fine, thank you.", "Yes, I do.", "See you."], answer: 1, explain: "体調をたずねる表現。I'm fine, thank you. と返す。" },
          { type: "order", q: "「私はケンです。」を並べ替えよう。", tokens: ["is", "name", "My", "Ken"], answer: ["My", "name", "is", "Ken"], explain: "My name is Ken." },
          { type: "input", q: "「私は東京の出身です。」の空所:「I'm ___ Tokyo.」", answers: ["from", "From"], explain: "出身は from を使う。I'm from Tokyo." },
          { type: "choice", q: "別れぎわのあいさつはどれ？", choices: ["Good morning.", "Nice to meet you.", "See you.", "How are you?"], answer: 2, explain: "See you.（またね）は別れのあいさつ。" },
        ],
      },
    ],
  },

  /* ===================== 中学生 ===================== */
  {
    id: "junior",
    stage: "中学生",
    color: "#2f7fd1",
    desc: "英文の語順ルールを体系的に理解し、必修文法と語彙を固める区分。",
    units: [
      {
        id: "jr-be-verb",
        title: "be動詞と一般動詞の使い分け",
        goal: "1つの文にbe動詞と一般動詞を混ぜず、肯定・否定・疑問を正しく作る。",
        diagnosis: "× I am like ~ がなぜ誤りか説明できますか？",
        lecture: [
          { h: "2種類の動詞", body: "be動詞（am/is/are）＝『〜だ／いる』、一般動詞＝『〜する』。1文に1つ。" },
          { h: "否定・疑問の作り方が違う", body: "be動詞: not を後ろ／文頭に出す。一般動詞: don't・doesn't／Do・Does を使う。" },
          { h: "判断の手順", body: "まず『状態か動作か』を見分け、どちらの動詞かを決めてから否定・疑問を作る。" },
        ],
        exercises: [
          {
            type: "choice",
            difficulty: "基礎",
            q: "誤りを含む文はどれ？",
            choices: ["She is a teacher.", "He doesn't play tennis.", "I am study English.", "Are you happy?", "選択肢に正解が無い"],
            answer: 2,
            explain: "I am study は be動詞 am と一般動詞 study の混在。正しくは I study English.（一般動詞の文に be動詞は不要）。",
            points: ["1つの文に動詞は1つ", "study は一般動詞 → am は不要", "正しくは I study English."],
          },
          {
            type: "order",
            difficulty: "標準",
            q: "「彼は犬が好きではありません。」を並べ替えよう。",
            tokens: ["doesn't", "He", "dogs", "like"],
            answer: ["He", "doesn't", "like", "dogs"],
            explain: "一般動詞の否定は『doesn't＋原形』。主語 He は3単現なので does を使い、動詞は原形 like に戻す。",
            points: ["like は一般動詞 → 否定は don't / doesn't", "主語 He は3人称単数 → doesn't", "doesn't の後ろの動詞は原形 like"],
          },
          {
            type: "input",
            difficulty: "基礎",
            q: "「あなたは学生ですか。」の文頭に入る語を書こう:「___ you a student?」",
            answers: ["Are", "are"],
            explain: "a student（名詞）が続く＝be動詞の文。be動詞の疑問文は be動詞を文頭に出す → Are you a student?",
            points: ["a student（名詞）→ be動詞の文", "be動詞の疑問文は be動詞を文頭に", "主語 you に合うのは are"],
          },
          {
            type: "choice",
            difficulty: "標準",
            q: "「Does she like music?」の答えとして正しいのは？",
            choices: ["Yes, she is.", "Yes, she does.", "Yes, she do.", "Yes, she likes.", "選択肢に正解が無い"],
            answer: 1,
            explain: "Does で始まる疑問文には does で答える。Yes, she does.",
            points: ["疑問文の最初の語を見る → Does", "Does の疑問文には does で答える", "主語 she に合わせて does"],
          },
        ],
      },
      {
        id: "jr-third-s",
        title: "三単現のs",
        goal: "主語が3人称単数のとき、一般動詞に s/es を付けるルールを定着させる。",
        diagnosis: "He play / He plays のどちらが正しいか即答できますか？",
        lecture: [
          { h: "3人称単数とは", body: "I・you 以外で1人（1つ）の主語：he, she, it, Ken, my dog など。" },
          { h: "sの付け方", body: "原則 +s。go→goes, watch→watches（o,s,x,ch,sh）。study→studies（子音+y）。have→has。" },
          { h: "否定・疑問では原形", body: "doesn't / Does を使うとき動詞は原形に戻る。He doesn't play." },
        ],
        exercises: [
          { type: "choice", q: "「My sister ___ to school by bus.」の空所は？", choices: ["go", "goes", "going", "gone"], answer: 1, explain: "主語が3単現。go→goes。" },
          { type: "input", q: "study を3単現の形にすると？", answers: ["studies"], explain: "子音+y は y→ies。studies。" },
          { type: "choice", q: "誤りを含む文は？", choices: ["He has a car.", "She watches TV.", "It rains a lot.", "Ken don't like fish."], answer: 3, explain: "Ken は3単現なので doesn't。Ken doesn't like fish." },
          { type: "order", q: "「私の父は毎朝コーヒーを飲みます。」を並べ替えよう。", tokens: ["drinks", "My father", "every morning", "coffee"], answer: ["My father", "drinks", "coffee", "every morning"], explain: "My father drinks coffee every morning." },
        ],
      },
      {
        id: "jr-past",
        title: "過去形（規則・不規則）",
        goal: "過去のことを表す動詞の形（-ed と不規則変化）を使い分ける。",
        diagnosis: "go の過去形、play の過去形をそれぞれ言えますか？",
        lecture: [
          { h: "規則動詞", body: "原則 +ed。like→liked, study→studied, stop→stopped。" },
          { h: "不規則動詞", body: "go→went, see→saw, have→had, eat→ate, get→got など。暗記が必要。" },
          { h: "否定・疑問は did", body: "didn't＋原形／Did＋主語＋原形。He didn't go. Did you see it?" },
        ],
        exercises: [
          { type: "choice", q: "「I ___ to Kyoto last week.」の空所は？", choices: ["go", "goes", "went", "going"], answer: 2, explain: "go の過去形は went。" },
          { type: "input", q: "study の過去形を書こう。", answers: ["studied"], explain: "子音+y は y→ied。studied。" },
          { type: "order", q: "「彼女は昨日テレビを見ませんでした。」を並べ替えよう。", tokens: ["didn't", "She", "TV", "watch", "yesterday"], answer: ["She", "didn't", "watch", "TV", "yesterday"], explain: "didn't の後ろは原形 watch。" },
          { type: "choice", q: "「Did you eat breakfast?」への答えで正しいのは？", choices: ["Yes, I did.", "Yes, I ate.", "Yes, I was.", "Yes, I do."], answer: 0, explain: "Did の疑問文には did で答える。" },
        ],
      },
      {
        id: "jr-progressive",
        title: "現在進行形",
        goal: "「〜している」を表す be動詞＋-ing の形を使えるようにする。",
        diagnosis: "「私は今、本を読んでいます」を英語で言えますか？",
        lecture: [
          { h: "形", body: "be動詞（am/is/are）＋動詞のing形。I am reading a book." },
          { h: "ing の作り方", body: "原則 +ing。make→making（e を取る）, run→running（子音重ねる）。" },
          { h: "意味", body: "『今まさに〜している』。状態動詞（like, know など）は普通使わない。" },
        ],
        exercises: [
          { type: "choice", q: "「They ___ soccer now.」の空所は？", choices: ["play", "plays", "are playing", "played"], answer: 2, explain: "now があり進行形。are playing。" },
          { type: "input", q: "run のing形を書こう。", answers: ["running"], explain: "短母音+子音は子音を重ねて running。" },
          { type: "order", q: "「彼女は手紙を書いています。」を並べ替えよう。", tokens: ["is", "She", "a letter", "writing"], answer: ["She", "is", "writing", "a letter"], explain: "She is writing a letter." },
          { type: "choice", q: "進行形にしにくい動詞はどれ？", choices: ["run", "study", "know", "play"], answer: 2, explain: "know（知っている）は状態動詞で進行形にしないのが普通。" },
        ],
      },
      {
        id: "jr-future",
        title: "未来表現（will / be going to）",
        goal: "will と be going to で未来のことを表現できるようにする。",
        diagnosis: "will と be going to の違いを説明できますか？",
        lecture: [
          { h: "will", body: "will＋動詞の原形。その場で決めた意志・予測。I will help you." },
          { h: "be going to", body: "be going to＋原形。前から決めていた予定・確実な予測。I'm going to study tonight." },
          { h: "否定・疑問", body: "will not(won't)／Will you ~? be動詞を使う be going to は be で否定・疑問。" },
        ],
        exercises: [
          { type: "choice", q: "「明日は雨が降るでしょう。」に合う文は？", choices: ["It rains tomorrow.", "It will rain tomorrow.", "It is rain tomorrow.", "It raining tomorrow."], answer: 1, explain: "未来の予測は will＋原形。" },
          { type: "order", q: "「私は今夜、宿題をするつもりです。」を並べ替えよう。", tokens: ["going to", "I'm", "my homework", "do", "tonight"], answer: ["I'm", "going to", "do", "my homework", "tonight"], explain: "be going to＋原形。" },
          { type: "input", q: "will not の短縮形を書こう。", answers: ["won't"], explain: "will not = won't。" },
          { type: "choice", q: "「前から決めていた予定」を表すのにふさわしいのは？", choices: ["will", "be going to", "can", "must"], answer: 1, explain: "前からの予定は be going to。" },
        ],
      },
      {
        id: "jr-modal",
        title: "助動詞（can / must / should）",
        goal: "can・must・should などの助動詞の意味と使い方を整理する。",
        diagnosis: "must と have to、should の違いが分かりますか？",
        lecture: [
          { h: "形は共通", body: "助動詞＋動詞の原形。否定は助動詞＋not。疑問は助動詞を文頭に。" },
          { h: "意味", body: "can=できる／してよい、must=しなければならない、should=すべき、may=してよい/かもしれない。" },
          { h: "must not と don't have to", body: "must not＝してはいけない（禁止）、don't have to＝する必要がない。意味が違う。" },
        ],
        exercises: [
          { type: "choice", q: "「You ___ finish this today.」（今日中に終えるべき）の空所は？", choices: ["can", "should", "may", "are"], answer: 1, explain: "『〜すべき』は should。" },
          { type: "order", q: "「ここで写真をとってはいけません。」を並べ替えよう。", tokens: ["take", "You", "pictures", "must not", "here"], answer: ["You", "must not", "take", "pictures", "here"], explain: "must not＝禁止。" },
          { type: "input", q: "「彼は泳げます。」の空所:「He ___ swim.」", answers: ["can"], explain: "『〜できる』は can。後ろは原形。" },
          { type: "choice", q: "「don't have to」の意味は？", choices: ["してはいけない", "する必要がない", "しなければならない", "したほうがよい"], answer: 1, explain: "don't have to＝する必要がない。" },
        ],
      },
      {
        id: "jr-perfect",
        title: "現在完了",
        goal: "have/has＋過去分詞で『完了・経験・継続』を表せるようにする。",
        diagnosis: "「私は3年間英語を勉強しています」を現在完了で言えますか？",
        lecture: [
          { h: "形", body: "have/has＋過去分詞。過去分詞は go→gone, see→seen など。" },
          { h: "3つの意味", body: "完了（just/already/yet）、経験（ever/never/before）、継続（for/since）。" },
          { h: "過去形との違い", body: "過去形は『過去の一点』、現在完了は『過去と今のつながり』を表す。" },
        ],
        exercises: [
          { type: "choice", q: "「I have ___ this movie before.」の空所は？", choices: ["see", "saw", "seen", "seeing"], answer: 2, explain: "現在完了は have＋過去分詞。see→seen。" },
          { type: "order", q: "「私は宿題をもう終えました。」を並べ替えよう。", tokens: ["have", "I", "finished", "already", "my homework"], answer: ["I", "have", "already", "finished", "my homework"], explain: "完了用法。already は have と過去分詞の間。" },
          { type: "input", q: "継続を表す『〜以来』を意味する語を書こう（接続詞・前置詞）。", answers: ["since", "Since"], explain: "since＝〜以来。継続用法でよく使う。" },
          { type: "choice", q: "「Have you ever been to Okinawa?」の意味は？", choices: ["沖縄に行く予定ですか", "沖縄に行ったことがありますか", "沖縄にいますか", "沖縄に行きましたか（昨日）"], answer: 1, explain: "ever＋現在完了で『経験』。" },
        ],
      },
      {
        id: "jr-compare",
        title: "比較（比較級・最上級）",
        goal: "-er/-est、more/most、as ~ as を使って比較表現を作る。",
        diagnosis: "good の比較級・最上級を言えますか？",
        lecture: [
          { h: "比較級・最上級", body: "短い語: +er / +est（tall→taller→tallest）。長い語: more / most。" },
          { h: "不規則変化", body: "good/well→better→best、many/much→more→most、bad→worse→worst。" },
          { h: "as ~ as / than", body: "比較級は than と、最上級は the と、同等は as ~ as と使う。" },
        ],
        exercises: [
          { type: "choice", q: "「This book is ___ than that one.」の空所は？", choices: ["interesting", "more interesting", "most interesting", "interestinger"], answer: 1, explain: "interesting は長い語なので more interesting。" },
          { type: "input", q: "good の最上級を書こう。", answers: ["best"], explain: "good→better→best（不規則）。" },
          { type: "order", q: "「富士山は日本でいちばん高い山です。」を並べ替えよう。", tokens: ["the highest", "Mt. Fuji", "in Japan", "is", "mountain"], answer: ["Mt. Fuji", "is", "the highest", "mountain", "in Japan"], explain: "最上級は the＋-est。" },
          { type: "choice", q: "「Tom is as tall as Ken.」の意味は？", choices: ["トムはケンより背が高い", "トムはケンと同じくらい背が高い", "トムはケンより背が低い", "トムはいちばん背が高い"], answer: 1, explain: "as ~ as は『同じくらい』。" },
        ],
      },
      {
        id: "jr-passive",
        title: "受動態",
        goal: "be動詞＋過去分詞で『〜される』を表せるようにする。",
        diagnosis: "「この本は多くの人に読まれています」を英語にできますか？",
        lecture: [
          { h: "形", body: "be動詞＋過去分詞。This book is read by many people." },
          { h: "by ~", body: "動作をする人・ものは by ~ で表す（言わなくてよいことも多い）。" },
          { h: "時制は be動詞で", body: "過去は was/were＋過去分詞。The house was built in 1990." },
        ],
        exercises: [
          { type: "choice", q: "「English ___ in many countries.」（話されている）の空所は？", choices: ["speaks", "is speaking", "is spoken", "spoke"], answer: 2, explain: "受動態 be＋過去分詞。speak→spoken。" },
          { type: "order", q: "「この寺は約400年前に建てられました。」を並べ替えよう。", tokens: ["was", "This temple", "about 400 years ago", "built"], answer: ["This temple", "was", "built", "about 400 years ago"], explain: "過去の受動態は was＋過去分詞。" },
          { type: "input", q: "「〜によって」を表す前置詞を書こう。", answers: ["by", "By"], explain: "受動態の動作主は by ~。" },
          { type: "choice", q: "「The window was broken.」の意味は？", choices: ["窓を割った", "窓が割られた", "窓を割るだろう", "窓を割っている"], answer: 1, explain: "was broken で『割られた』。" },
        ],
      },
      {
        id: "jr-infinitive",
        title: "不定詞と動名詞",
        goal: "to＋原形と動詞のing形を、用法ごとに使い分ける。",
        diagnosis: "want と enjoy の後ろは to不定詞・動名詞のどちらですか？",
        lecture: [
          { h: "不定詞の3用法", body: "名詞的（〜すること）、形容詞的（〜するための）、副詞的（〜するために／して）。" },
          { h: "動名詞", body: "動詞のing形で『〜すること』。主語・目的語になる。Reading is fun." },
          { h: "後ろの形が決まる動詞", body: "want/hope/decide＋to不定詞。enjoy/finish/stop＋動名詞。" },
        ],
        exercises: [
          { type: "choice", q: "「I want ___ a doctor.」の空所は？", choices: ["be", "to be", "being", "been"], answer: 1, explain: "want の後ろは to不定詞。to be。" },
          { type: "choice", q: "「I enjoyed ___ tennis.」の空所は？", choices: ["play", "to play", "playing", "played"], answer: 2, explain: "enjoy の後ろは動名詞。playing。" },
          { type: "order", q: "「私は英語を勉強するために早起きします。」を並べ替えよう。", tokens: ["to study", "I get up early", "English"], answer: ["I get up early", "to study", "English"], explain: "副詞的用法『〜するために』。" },
          { type: "input", q: "「読書は楽しい。」の主語部分:「___ is fun.」（動名詞1語）", answers: ["Reading"], explain: "動名詞 Reading が主語。" },
        ],
      },
      {
        id: "jr-relative",
        title: "関係代名詞",
        goal: "who / which / that を使って名詞を後ろから説明できるようにする。",
        diagnosis: "「向こうで走っている男の子」を英語で言えますか？",
        lecture: [
          { h: "はたらき", body: "名詞（先行詞）を後ろから説明する。2つの文を1つにつなぐ。" },
          { h: "使い分け", body: "人→who、もの→which、人もの両方→that。" },
          { h: "主格と目的格", body: "後ろが『動詞』なら主格、後ろが『主語＋動詞』なら目的格（省略可）。" },
        ],
        exercises: [
          {
            type: "choice",
            difficulty: "基礎",
            q: "「I have a friend ___ lives in Osaka.」の空所に入る最も適切な語は？",
            choices: ["who", "which", "what", "whose", "選択肢に正解が無い"],
            answer: 0,
            explain: "先行詞 a friend は『人』、空所の後ろは動詞 lives ＝ 主語が欠けている → 主格の who。",
            points: ["先行詞を確認する → a friend（人）", "空所の後ろを見る → lives（動詞）＝主語が欠けている", "人＋主格 → who"],
          },
          {
            type: "choice",
            difficulty: "標準",
            q: "「The artist uses the guitar ( ) he bought in the U.S.」の空所に入る最も適切な語は？",
            choices: ["who", "it", "whom", "which", "選択肢に正解が無い"],
            answer: 3,
            explain: "先行詞 the guitar は『もの』、空所の後ろは he bought（主語＋動詞で目的語が欠けている）→ 目的格の which。",
            points: [
              "先行詞を確認する → the guitar（もの）",
              "空所の後ろを見る → he bought（S＋V で目的語が欠けている）→ 目的格",
              "もの＋目的格 → which（that も可）。it は2文をつなげないので不可",
            ],
            more: "関係代名詞は『先行詞が人かものか』×『後ろが動詞から始まる（主格）か、主語＋動詞（目的格）か』で決まる。ここは『もの＋目的格』なので which。目的格の関係代名詞は省略もできる（the guitar he bought）。",
          },
          {
            type: "order",
            difficulty: "標準",
            q: "「あれは300年前に建てられた家です。」を並べ替えよう。",
            tokens: ["that", "That", "was built", "is", "a house", "300 years ago"],
            answer: ["That", "is", "a house", "that", "was built", "300 years ago"],
            explain: "That is a house / that was built 300 years ago. 関係代名詞 that が先行詞 a house を後ろから説明。",
            points: ["まず文の骨格 That is a house を作る", "a house を説明する節を後ろにつなぐ", "先行詞（もの）＋主格 → that／which"],
          },
          {
            type: "input",
            difficulty: "発展",
            q: "「これは私が昨日買った本です。」の関係代名詞を省略した形:「This is the book ___ bought yesterday.」の空所に入る語を書こう。",
            answers: ["I"],
            explain: "目的格の関係代名詞（which/that）は省略できる。省略すると the book の後ろにすぐ主語 I が来る。",
            points: ["元の文は This is the book which I bought yesterday.", "目的格の関係代名詞は省略可能", "省略すると『名詞＋主語＋動詞』の形になる"],
          },
        ],
      },
      {
        id: "jr-vocab",
        title: "頻出英単語（中3レベル）",
        goal: "入試で正答率が下がりやすい中3頻出語を、見て1秒で意味が出るまで定着させる。",
        diagnosis: "certainly / immediately / opportunity の意味が即答できますか？",
        lecture: [
          { h: "単語は英語の土台", body: "英単語の意味とスペルが分かると、長文読解も英作文も解けるようになる。まず語彙から固める。" },
          { h: "復習間隔を広げる", body: "短時間で何度も思い出すサイクルを回す。復習は『翌日 → 3日後 → 1週間後』と間隔を段階的に広げると長期記憶になる。" },
          { h: "多角的に・双方向で", body: "見る・聞く・書く・話すの複数方向から触れ、英→日／日→英の双方向で覚える。" },
        ],
        exercises: [
          { type: "choice", q: "「certainly」の意味は？", choices: ["確かに・きっと", "めったに〜ない", "おそらく違う", "ときどき"], answer: 0, explain: "certainly＝確かに、きっと。正答率が下がりやすい頻出副詞。" },
          { type: "choice", q: "「immediately」の意味は？", choices: ["ゆっくりと", "直ちに・すぐに", "最近", "二度と"], answer: 1, explain: "immediately＝直ちに、すぐに。" },
          { type: "choice", q: "「opportunity」の意味は？", choices: ["問題", "機会・チャンス", "責任", "結果"], answer: 1, explain: "opportunity＝機会、チャンス。" },
          { type: "choice", q: "「describe」の意味は？", choices: ["〜を破壊する", "〜の特徴を述べる", "〜を予約する", "〜を避ける"], answer: 1, explain: "describe O＝Oの特徴を述べる、描写する。" },
          { type: "choice", q: "「although」の意味は？", choices: ["〜なので", "〜だけれども", "〜する間に", "〜するとすぐに"], answer: 1, explain: "although＝〜だけれども（接続詞）。" },
          { type: "choice", q: "「temperature」の意味は？", choices: ["気温・温度", "天気", "気圧", "季節"], answer: 0, explain: "temperature＝気温、温度。つづりに注意。" },
          { type: "choice", q: "「unbelievable」の意味は？", choices: ["役に立つ", "信じられない（ほどの）", "予想通りの", "価値のない"], answer: 1, explain: "un(否定)＋believable で『信じられない』。" },
          { type: "choice", q: "「squirrel」の意味は？", choices: ["ワシ", "リス", "カエル", "ネズミ"], answer: 1, explain: "squirrel＝リス。つづりが難しい頻出語。" },
          { type: "input", q: "「家具」を表す英単語を書こう（f で始まる）。", answers: ["furniture", "Furniture"], explain: "furniture＝家具。数えられない名詞。" },
          { type: "input", q: "「ハサミ」を表す英単語を書こう。", answers: ["scissors", "Scissors"], explain: "scissors＝ハサミ。つねに複数形で使う。" },
        ],
      },
    ],
  },

  /* ===================== 高校生 ===================== */
  {
    id: "senior",
    stage: "高校生",
    color: "#c9582b",
    desc: "文法・語法・読解・長文・語彙を統合し、入試で問われる総合力を完成させる区分。",
    units: [
      {
        id: "sr-sentence",
        title: "文の要素と5文型",
        goal: "S・V・O・C・Mを見抜き、英文の骨格（5文型）を判断できるようにする。",
        diagnosis: "SVOとSVOOとSVOCの違いを説明できますか？",
        lecture: [
          { h: "文の要素", body: "S(主語)・V(動詞)・O(目的語)・C(補語)・M(修飾語)。Mを外すと骨格が見える。" },
          { h: "5文型", body: "①SV ②SVC ③SVO ④SVOO ⑤SVOC。Cは『S=C / O=C』の関係。" },
          { h: "見分けのコツ", body: "be動詞・become→C、give型→OO、make/call/keep→OC。" },
        ],
        exercises: [
          {
            type: "label",
            difficulty: "基礎",
            instruction: "各まとまりに文の要素（S / V / O / C / M）を割り当てよう。",
            sentence: "Birds sing every morning.",
            chunks: ["Birds", "sing", "every morning"],
            labels: ["S", "V", "M"],
            explain: "Birds(S) sing(V) every morning(M)。O も C もないので第1文型 SV（M は文型に数えない）。",
            points: ["動詞 sing を見つける", "その前の Birds が主語(S)", "every morning は『いつ』を表す修飾語(M)"],
          },
          {
            type: "label",
            difficulty: "標準",
            instruction: "各まとまりに文の要素（S / V / O / C / M）を割り当てよう。",
            sentence: "He gave me a present.",
            chunks: ["He", "gave", "me", "a present"],
            labels: ["S", "V", "O", "O"],
            explain: "He(S) gave(V) me(O) a present(O)。目的語が2つ＝第4文型 SVOO。",
            points: ["動詞 gave を見つける", "give 型の動詞は目的語を2つとる", "me（人）と a present（もの）がどちらも O"],
            more: "give / show / teach / send などは『人に・ものを』の2つの目的語をとり SVOO になる。SVOO は SVO＋to/for ～ に書き換えられる（gave a present to me）。",
          },
          {
            type: "label",
            difficulty: "発展",
            instruction: "各まとまりに文の要素（S / V / O / C / M）を割り当てよう。",
            sentence: "The news made her sad.",
            chunks: ["The news", "made", "her", "sad"],
            labels: ["S", "V", "O", "C"],
            explain: "The news(S) made(V) her(O) sad(C)。her＝sad の関係 → 第5文型 SVOC。",
            points: ["動詞 made を見つける", "made の後ろに『her＝sad』の関係がある", "O と C の間に『＝』が成り立てば SVOC"],
            more: "make / call / keep / find などは SVOC をとる。SVOO（O≠O）と SVOC（O＝C）の違いは『2つの語の間にイコールが成り立つか』で見分ける。",
          },
          {
            type: "choice",
            difficulty: "標準",
            q: "「She became a doctor.」の文型は？",
            choices: ["第1文型 SV", "第2文型 SVC", "第3文型 SVO", "第5文型 SVOC"],
            answer: 1,
            explain: "She＝a doctor の関係。become の後ろは補語(C) → 第2文型 SVC。",
            points: ["動詞 became を確認", "She＝a doctor が成り立つ", "be動詞・become の後ろは補語(C)"],
          },
        ],
      },
      {
        id: "sr-tense",
        title: "時制の整理（完了形の応用）",
        goal: "過去完了・未来完了・完了進行形まで含め、時の前後関係を整理する。",
        diagnosis: "過去完了（had＋過去分詞）をどんな時に使うか説明できますか？",
        lecture: [
          { h: "過去完了", body: "had＋過去分詞。過去のある時点より『さらに前』。大過去・完了・経験・継続。" },
          { h: "未来完了", body: "will have＋過去分詞。未来のある時点までに『〜し終えている』。" },
          { h: "完了進行形", body: "have been＋-ing。動作の継続を強調。I have been waiting for an hour." },
        ],
        exercises: [
          { type: "choice", q: "「When I arrived, the train had already ___.」の空所は？", choices: ["leave", "left", "leaving", "leaves"], answer: 1, explain: "過去完了 had＋過去分詞。leave→left。" },
          { type: "order", q: "「彼女は2時間ずっと走り続けています。」を並べ替えよう。", tokens: ["has been", "She", "for two hours", "running"], answer: ["She", "has been", "running", "for two hours"], explain: "完了進行形 have been＋-ing。" },
          { type: "input", q: "「未来のある時点までに完了」を表す形:「will ___ finished」", answers: ["have"], explain: "未来完了 will have＋過去分詞。" },
          { type: "choice", q: "過去完了が表すのは？", choices: ["未来より後", "過去のある時点よりさらに前", "現在の習慣", "今まさに進行中"], answer: 1, explain: "過去完了は『過去の過去（大過去）』などを表す。" },
        ],
      },
      {
        id: "sr-modal-perfect",
        title: "助動詞＋have＋過去分詞",
        goal: "must have / should have / could have など過去への推量・後悔を理解する。",
        diagnosis: "「〜したはずだ」「〜すべきだった」を英語で言えますか？",
        lecture: [
          { h: "形", body: "助動詞＋have＋過去分詞。過去のことへの推量・評価を表す。" },
          { h: "意味", body: "must have＝〜したにちがいない、should have＝〜すべきだった（後悔）、can't have＝〜したはずがない、may/might have＝〜したかもしれない。" },
          { h: "ニュアンス", body: "現在から振り返って過去を推量・評価する表現。" },
        ],
        exercises: [
          { type: "choice", q: "「You ___ studied harder.（もっと勉強すべきだった）」の空所は？", choices: ["must have", "should have", "can't have", "may have"], answer: 1, explain: "should have＋過去分詞＝〜すべきだった（後悔）。" },
          { type: "choice", q: "「He must have missed the bus.」の意味は？", choices: ["バスに乗り遅れるべきだ", "バスに乗り遅れたにちがいない", "バスに乗り遅れるかもしれない", "バスに乗り遅れるはずがない"], answer: 1, explain: "must have＝〜したにちがいない。" },
          { type: "order", q: "「彼女がそれを言ったはずがない。」を並べ替えよう。", tokens: ["have", "She", "said", "can't", "that"], answer: ["She", "can't", "have", "said", "that"], explain: "can't have＋過去分詞＝〜したはずがない。" },
          { type: "input", q: "「〜したかもしれない」を表す:「may ___ done」の空所。", answers: ["have"], explain: "may have＋過去分詞。" },
        ],
      },
      {
        id: "sr-subjunctive",
        title: "仮定法",
        goal: "現在の事実と異なる仮定（仮定法過去）と過去の仮定（仮定法過去完了）を使い分ける。",
        diagnosis: "「もし時間があれば手伝うのに」を仮定法で言えますか？",
        lecture: [
          { h: "仮定法過去", body: "現在の事実に反する仮定。If＋過去形, S＋would/could＋原形。If I had time, I would help you." },
          { h: "仮定法過去完了", body: "過去の事実に反する仮定。If＋had＋過去分詞, S＋would have＋過去分詞。" },
          { h: "be動詞は were", body: "仮定法では主語にかかわらず were を使うのが基本。If I were you, ..." },
        ],
        exercises: [
          {
            type: "choice",
            difficulty: "基礎",
            q: "「If I ___ rich, I would travel the world.」の空所に入る最も適切な語は？",
            choices: ["am", "was", "were", "will be", "選択肢に正解が無い"],
            answer: 2,
            explain: "主節に would＋原形があり、現在の事実に反する仮定＝仮定法過去。仮定法では主語にかかわらず be動詞は were。",
            points: ["主節に『would＋原形』→ 仮定法過去", "現在の事実（私は金持ちでない）に反する仮定", "仮定法の be動詞は were（I でも were）"],
          },
          {
            type: "order",
            difficulty: "標準",
            q: "「もしあなたが私だったら、どうしますか。」を並べ替えよう。",
            tokens: ["were", "If", "you", "me", "what would you do"],
            answer: ["If", "you", "were", "me", "what would you do"],
            explain: "If you were me, what would you do? if節は『If＋S＋過去形』、主節は『would＋原形』。",
            points: ["if節の形：If＋主語＋過去形（were）", "主節の形：would＋動詞の原形", "be動詞は were を使う"],
          },
          {
            type: "choice",
            difficulty: "発展",
            q: "「If I had studied, I would have passed.」が表す『実際の事実』は？",
            choices: ["これから勉強する", "実際は勉強せず、不合格だった", "勉強して合格した", "勉強中である"],
            answer: 1,
            explain: "『If＋had＋過去分詞, would have＋過去分詞』＝仮定法過去完了。過去の事実に反する仮定なので、実際は『勉強せず不合格』。",
            points: ["『had＋過去分詞 … would have＋過去分詞』→ 仮定法過去完了", "過去の事実に反する仮定を表す", "仮定の逆＝実際は『勉強しなかった・不合格だった』"],
            more: "仮定法過去（現在の事実に反する）は『If＋過去形, would＋原形』。仮定法過去完了（過去の事実に反する）は『If＋had＋過去分詞, would have＋過去分詞』。文が表す『仮定』の逆が『実際の事実』。",
          },
          {
            type: "input",
            difficulty: "標準",
            q: "仮定法過去完了の if 節は「If＋S＋had＋___」。空所に入る形を日本語で書こう。",
            answers: ["過去分詞"],
            explain: "仮定法過去完了の if 節は『If＋S＋had＋過去分詞』。",
            points: ["仮定法過去完了は過去の事実に反する仮定", "if節：If＋S＋had＋過去分詞", "主節：S＋would have＋過去分詞"],
          },
        ],
      },
      {
        id: "sr-relative-adv",
        title: "関係詞（関係副詞・whatなど）",
        goal: "where/when/why/how、関係代名詞 what、複合関係詞まで使えるようにする。",
        diagnosis: "the place where と the place which の違いが分かりますか？",
        lecture: [
          { h: "関係副詞", body: "where(場所)・when(時)・why(理由)・how(方法)。後ろは完全な文。" },
          { h: "関係代名詞 what", body: "『〜するもの・こと』。先行詞を含む。what I want＝私がほしいもの。" },
          { h: "関係副詞 vs 関係代名詞", body: "後ろが完全文→関係副詞、後ろにS/Oの欠け→関係代名詞。" },
        ],
        exercises: [
          { type: "choice", q: "「This is the town ___ I was born.」の空所は？", choices: ["which", "where", "what", "who"], answer: 1, explain: "場所＋完全文なので関係副詞 where。" },
          { type: "choice", q: "「___ he said surprised us.」の空所は？", choices: ["What", "Which", "That", "Where"], answer: 0, explain: "先行詞を含む what。『彼が言ったこと』。" },
          { type: "order", q: "「これが彼が遅刻した理由です。」を並べ替えよう。", tokens: ["the reason", "This", "is", "why", "he was late"], answer: ["This", "is", "the reason", "why", "he was late"], explain: "理由＋完全文なので why。" },
          { type: "input", q: "『方法』を表す関係副詞を1語書こう。", answers: ["how", "How"], explain: "the way / how（方法）。" },
        ],
      },
      {
        id: "sr-participle",
        title: "分詞と分詞構文",
        goal: "現在分詞・過去分詞の名詞修飾と、分詞構文の意味を読み取れるようにする。",
        diagnosis: "the running boy と the broken window の分詞の違いが分かりますか？",
        lecture: [
          { h: "分詞の名詞修飾", body: "現在分詞(-ing)＝『〜している』能動、過去分詞＝『〜される/された』受動。" },
          { h: "位置", body: "1語なら名詞の前、2語以上なら名詞の後ろから修飾。" },
          { h: "分詞構文", body: "接続詞＋S＋Vを分詞で簡潔に。時・理由・条件・付帯状況などを表す。" },
        ],
        exercises: [
          {
            type: "choice",
            difficulty: "基礎",
            q: "「the language ___ in Brazil」（ブラジルで話されている言語）の空所は？",
            choices: ["speaking", "spoken", "speak", "to speak"],
            answer: 1,
            explain: "『話されている』は受動の関係なので過去分詞 spoken。",
            points: ["language と speak の関係を考える", "言語は『話される』側＝受動", "受動の名詞修飾は過去分詞"],
          },
          {
            type: "choice",
            difficulty: "標準",
            q: "「___ in the park, I met Tom.」（公園を歩いていて）の空所は？",
            choices: ["Walk", "Walked", "Walking", "To walk"],
            answer: 2,
            explain: "分詞構文。主語 I は『歩く』側＝能動なので現在分詞 Walking。",
            points: ["接続詞＋S＋V を分詞で簡潔にした形＝分詞構文", "意味上の主語 I と walk は能動の関係", "能動なら現在分詞 -ing"],
            more: "分詞構文は『When I walked in the park, I met Tom.』の接続詞＋主語を省き、動詞を分詞にした形。意味上の主語と動詞が能動なら現在分詞、受動なら過去分詞。",
          },
          {
            type: "choice",
            difficulty: "標準",
            q: "「Look at the sleeping baby.」の sleeping のはたらきは？",
            choices: ["述語動詞", "名詞", "baby を修飾する現在分詞", "前置詞"],
            answer: 2,
            explain: "sleeping は名詞 baby を前から修飾する現在分詞（形容詞のはたらき）。",
            points: ["文の述語動詞は Look", "sleeping は baby の直前にある", "1語の分詞は名詞の前から修飾する"],
          },
          {
            type: "input",
            difficulty: "発展",
            q: "「壊された窓」を表す「the ___ window」の空所に入る過去分詞1語を書こう。",
            answers: ["broken", "Broken"],
            explain: "break→broken。窓は『壊される』側なので受動を表す過去分詞 broken。",
            points: ["window と break の関係を考える", "窓は『壊される』側＝受動", "受動の名詞修飾は過去分詞 broken"],
          },
        ],
      },
      {
        id: "sr-reading-1",
        title: "英文読解①：一文の構造をとらえる",
        goal: "長い一文でも主語(S)と述語動詞(V)を見抜き、修飾を切り分けて正確に読む。",
        diagnosis: "長い主語の文で、どこまでが主語か見抜けますか？",
        lecture: [
          { h: "まずSとVを探す", body: "文の骨格はS＋V。前置詞句・関係詞節などの修飾を( )でくくると骨格が見える。" },
          { h: "長い主語に注意", body: "主語が句や節で長くなることがある。動詞の直前までが主語。" },
          { h: "ステップで読む", body: "①Sは何か ②Vは何か ③文型は何か、の順に必ず確認してから意味をとる。" },
        ],
        exercises: [
          {
            type: "steps",
            difficulty: "基礎",
            passage: "The book on the desk is mine.",
            instruction: "必ずステップ1〜2を踏んでから設問に答えること。",
            steps: [
              { q: "ステップ1：この文の主語(S)はどこまで？", choices: ["The book", "The book on the desk", "the desk", "mine"], answer: 1, hint: "on the desk は book を後ろから修飾する句。動詞の直前までが主語。" },
              { q: "ステップ2：この文の述語動詞(V)はどれ？", choices: ["book", "on", "is", "mine"], answer: 2, hint: "be動詞 is が述語動詞。" },
            ],
            main: {
              q: "設問：この文の文型は？",
              choices: ["第1文型 SV", "第2文型 SVC", "第3文型 SVO", "第5文型 SVOC"],
              answer: 1,
              explain: "The book on the desk (S) / is (V) / mine (C) → 第2文型 SVC。",
              points: ["修飾語句 on the desk を ( ) でくくる", "残った骨格 The book is mine を見る", "is は be動詞 → 後ろは補語(C)"],
              more: "主語が句で長くなっても、動詞の直前までが主語。be動詞の後ろは『S＝○○』の関係になる補語(C)。The book ＝ mine なので第2文型 SVC。",
            },
          },
          {
            type: "steps",
            difficulty: "標準",
            passage: "What he said yesterday surprised everyone.",
            instruction: "必ずステップ1〜2を踏んでから設問に答えること。",
            steps: [
              { q: "ステップ1：この文の主語(S)はどこまで？", choices: ["What", "What he said yesterday", "he", "everyone"], answer: 1, hint: "What he said yesterday（彼が昨日言ったこと）全体がひとかたまりの名詞節＝主語。" },
              { q: "ステップ2：この文の述語動詞(V)はどれ？", choices: ["said", "yesterday", "surprised", "everyone"], answer: 2, hint: "said は名詞節の中の動詞。文全体の述語動詞は surprised。" },
            ],
            main: {
              q: "設問：この文の意味として正しいものは？",
              choices: ["彼は昨日みんなを驚かせた", "彼が昨日言ったことがみんなを驚かせた", "みんなが彼に昨日言ったことを驚いた", "彼は昨日驚いた"],
              answer: 1,
              explain: "What he said yesterday（S）surprised（V）everyone（O）。『彼が昨日言ったことが、みんなを驚かせた』。",
              points: ["関係代名詞 what は『〜すること/もの』の名詞節をつくる", "名詞節の中の動詞 said と、文の述語動詞 surprised を区別する", "S＋V＋O の第3文型としてとらえる"],
              more: "文頭の What 節が長い主語になるパターン。節の中の動詞（said）に引きずられず、文全体の述語動詞（surprised）を見抜けるかがポイント。",
            },
          },
          {
            type: "label",
            difficulty: "発展",
            instruction: "各まとまりに文の要素（S / V / O / C / M）を割り当てよう。",
            sentence: "The students studying abroad miss their families.",
            chunks: ["The students studying abroad", "miss", "their families"],
            labels: ["S", "V", "O"],
            explain: "The students studying abroad(S) miss(V) their families(O)。studying abroad は主語を修飾する分詞句。第3文型 SVO。",
            points: ["studying abroad は students を修飾する分詞句 → 主語の一部", "述語動詞は miss", "miss の目的語は their families"],
          },
        ],
      },
      {
        id: "sr-reading-2",
        title: "英文読解②：文と文の論理関係",
        goal: "ディスコースマーカーから因果・対比・例示などの論理関係を読み取る。",
        diagnosis: "however と therefore は文の流れをどう変えますか？",
        lecture: [
          { h: "対比・逆接", body: "however, but, although, while＝前と『逆』の内容が来る合図。" },
          { h: "因果", body: "therefore, so, because, since＝原因と結果のつながりを示す。" },
          { h: "追加・例示", body: "moreover, in addition＝追加、for example, such as＝具体例。" },
        ],
        exercises: [
          {
            type: "steps",
            difficulty: "基礎",
            passage: "It was raining hard. ( A ), we decided to go out for lunch.",
            instruction: "ステップを踏んで、空所Aに入るマーカーを判断しよう。",
            steps: [
              { q: "ステップ1：前の文「雨が激しく降っていた」と後の文「昼食に外出することにした」の関係は？", choices: ["順当な結果（だから外出した）", "逆の流れ（なのに外出した）", "具体例の追加", "理由の説明"], answer: 1, hint: "『雨が激しい』なら普通は外出を控える。なのに外出した＝逆接。" },
            ],
            main: {
              q: "設問：空所( A )に入る最も適切な語は？",
              choices: ["Therefore", "However", "For example", "Because"],
              answer: 1,
              explain: "前後が『雨 → なのに外出』と逆の流れなので、逆接の However が適切。",
              points: ["前の文と後の文の内容の向きを比べる", "順当なら因果(Therefore)、逆なら逆接(However)", "ここは『激しい雨 なのに 外出』＝逆接"],
              more: "ディスコースマーカーは、前後の文の論理関係を示す道しるべ。However/but＝逆接、Therefore/so＝結果、For example＝例示、Because/since＝理由。前後の内容の『向き』を比べて判断する。",
            },
          },
          {
            type: "steps",
            difficulty: "標準",
            passage: "Online learning has many benefits. ( B ), it allows students to study at their own pace.",
            instruction: "ステップを踏んで、空所Bに入るマーカーを判断しよう。",
            steps: [
              { q: "ステップ1：前の文は『多くの利点がある』。後の文『自分のペースで学べる』はその何にあたる？", choices: ["反対の内容", "利点の具体例", "原因", "結論"], answer: 1, hint: "『多くの利点がある』→『（例えば）自分のペースで学べる』。後の文は利点の一つ＝具体例。" },
            ],
            main: {
              q: "設問：空所( B )に入る最も適切な語句は？",
              choices: ["However", "For example", "In contrast", "Nevertheless"],
              answer: 1,
              explain: "『多くの利点がある』→ その具体例として『自分のペースで学べる』。例示の For example が適切。",
              points: ["前の文が『一般的な主張』、後の文が『その中身』なら例示", "For example / for instance＝具体例の合図", "However / In contrast / Nevertheless はすべて逆接なので不適"],
            },
          },
          {
            type: "choice",
            difficulty: "発展",
            q: "「The plan looked perfect on paper. Nevertheless, it failed completely.」の2文の関係は？",
            choices: ["原因と結果（だから失敗した）", "逆接（完璧に見えた のに 失敗した）", "具体例の追加", "言い換え"],
            answer: 1,
            explain: "Nevertheless は『それにもかかわらず』。『完璧に見えた』のに『完全に失敗した』＝逆接。",
            points: ["Nevertheless は逆接のマーカー", "前『完璧に見えた』と後『失敗した』は逆向き", "予想を裏切る展開を示す"],
            more: "逆接マーカーには but / however / yet / nevertheless / still / although / though などがある。これらを見たら『前と逆の内容が来る』と身構えて読む。",
          },
        ],
      },
      {
        id: "sr-long-reading",
        title: "英文読解③：段落のつながりと長文演習",
        goal: "段落ごとの役割（主張・具体・反論・結論）をつかみ、長文の論理展開を追う。",
        diagnosis: "長文で『筆者の主張』がどこにあるか見つけられますか？",
        lecture: [
          { h: "段落の役割", body: "各段落は『主張』『具体例』『反論への対応』『結論』など役割を持つ。" },
          { h: "トピックセンテンス", body: "段落の最初（または最後）の文が要点であることが多い。" },
          { h: "設問タイプ別の解法", body: "内容一致は本文と照合、指示語は直前を確認、空所補充は前後の論理を確認。" },
        ],
        exercises: [
          {
            type: "steps",
            difficulty: "標準",
            passage:
              "Many people believe that working long hours leads to success. However, recent studies show the opposite. Workers who take regular breaks are often more productive than those who do not. For example, a short rest every hour can improve concentration. Therefore, smart scheduling matters more than total hours.",
            instruction: "段落の流れを追ってから設問に答えよう。",
            steps: [
              { q: "ステップ1：第1文は段落の中でどんな役割？", choices: ["筆者の最終的な主張", "世間の通念（このあと反論される）", "具体例", "結論"], answer: 1, hint: "Many people believe ～ は『多くの人はこう思っている』という通念。直後の However で反論が来る。" },
              { q: "ステップ2：For example で始まる文の役割は？", choices: ["新しい主張", "前の内容の具体例", "反対意見", "結論"], answer: 1, hint: "For example は直前の『休憩をとる人の方が生産的』の具体例。" },
            ],
            main: {
              q: "設問：この段落で筆者が最も伝えたいこと（主張）は？",
              choices: [
                "長時間働くほど成功する",
                "総労働時間より、賢いスケジュール（休憩のとり方）が大切だ",
                "休憩は生産性を下げる",
                "studyは信用できない",
              ],
              answer: 1,
              explain: "通念（長時間＝成功）→ However で反論 → 具体例 → Therefore で結論。筆者の主張は最後の『賢いスケジュールが大切』。",
              points: ["『通念 → However → 反論 → 例 → Therefore → 結論』の型を追う", "筆者の主張は通念ではなく反論側にある", "Therefore の後ろが段落の結論＝主張"],
              more: "論説文では『多くの人は～と思う（通念）。しかし～（反論）』という型が頻出。筆者の主張は通念ではなく『However/But の後ろ』にあることが多い。結論は Therefore/Thus などの後ろに置かれる。",
            },
          },
          {
            type: "choice",
            difficulty: "基礎",
            q: "段落の要点（トピックセンテンス）が書かれていることが多いのは？",
            choices: ["段落の真ん中", "段落の最初か最後", "本文のタイトルだけ", "脚注"],
            answer: 1,
            explain: "トピックセンテンスは段落の最初か最後に置かれることが多い。まずそこを読むと段落の役割がつかめる。",
            points: ["各段落の最初の文をまず読む", "なければ最後の文を確認する", "そこが段落の『言いたいこと』"],
          },
          {
            type: "choice",
            difficulty: "標準",
            q: "下線部の指示語（it, this, that など）の内容を答えるとき、最初に見るべきは？",
            choices: ["文章全体の最後", "直前の文や語句", "タイトル", "次の段落"],
            answer: 1,
            explain: "指示語は原則として直前に出てきた内容を指す。まず直前を確認し、代入して意味が通るか試す。",
            points: ["指示語は『直前』を指すのが原則", "候補を指示語の位置に代入してみる", "意味が自然に通るか確認する"],
          },
          {
            type: "choice",
            difficulty: "発展",
            q: "内容一致問題で最も確実な解き方は？",
            choices: ["勘で選ぶ", "選択肢を本文と1つずつ照合し、根拠の箇所を見つける", "最初の選択肢を選ぶ", "長い選択肢を選ぶ"],
            answer: 1,
            explain: "選択肢ごとに本文の該当箇所を探し、『言い換えになっているか』『言い過ぎ・すり替えがないか』を確認する。",
            points: ["選択肢を1つずつ本文と照合する", "本文に根拠の文を必ず見つける", "『言い過ぎ』『すり替え』の選択肢を消す"],
          },
        ],
      },
      {
        id: "sr-vocab",
        title: "英単語（入試レベル）",
        goal: "入試頻出語を『見て1秒で意味が出る』レベルにし、記憶度を管理する。",
        diagnosis: "次の語の意味が即答できますか：enhance / substantial / perceive。",
        lecture: [
          { h: "記憶度で管理", body: "『覚えた／うろ覚え／苦手』に仕分け、うろ覚え・苦手を高速反復する。" },
          { h: "1秒で思い出す", body: "長文・英作文で使うには『見た瞬間に意味が出る』速さが必要。" },
          { h: "語源・派生で増やす", body: "接頭辞・接尾辞や派生語をまとめて覚えると効率がよい。" },
        ],
        exercises: [
          { type: "choice", q: "「enhance」の意味は？", choices: ["減らす", "高める・向上させる", "破壊する", "延期する"], answer: 1, explain: "enhance＝高める、向上させる。" },
          { type: "choice", q: "「substantial」の意味は？", choices: ["かなりの・相当な", "わずかな", "一時的な", "人工的な"], answer: 0, explain: "substantial＝かなりの、相当な。" },
          { type: "choice", q: "「perceive」の意味は？", choices: ["許す", "知覚する・気づく", "支払う", "続ける"], answer: 1, explain: "perceive＝知覚する、気づく。" },
          { type: "input", q: "「demonstrate」の意味を日本語で書こう（『〜を…する』の動詞）。", answers: ["証明する", "示す", "実証する", "証明する・示す", "デモをする"], explain: "demonstrate＝（実例で）示す・証明する。" },
        ],
      },
      {
        id: "sr-vocab-freq",
        title: "頻出英単語（高2・高3レベル）",
        goal: "正答率が4〜5割まで下がる入試頻出語を、長文・英作文で使えるレベルにする。",
        diagnosis: "obtain / whereas / distribute の意味が即答できますか？",
        lecture: [
          { h: "正答率が低い＝差がつく", body: "ここで扱う語は多くの受験生が間違える。確実に覚えればライバルに差をつけられる。" },
          { h: "1秒で意味を出す", body: "長文・英作文で使うには『見た瞬間に意味が出る』速さが必要。アウトプット型で反復する。" },
          { h: "語源・派生で広げる", body: "接頭辞・接尾辞や語源に着目すると、初見の語も意味を推測できるようになる。" },
        ],
        exercises: [
          { type: "choice", q: "「obtain」の意味は？", choices: ["〜を失う", "〜を得る・手に入れる", "〜を疑う", "〜を避ける"], answer: 1, explain: "obtain O＝Oを得る、手に入れる。正答率42%の難語。" },
          { type: "choice", q: "「purchase」の意味は？", choices: ["〜を購入する", "〜を返品する", "〜を比較する", "〜を借りる"], answer: 0, explain: "purchase O＝Oを購入する、買う。" },
          { type: "choice", q: "「whereas」の意味は？", choices: ["〜なので", "〜する一方で・〜のに対し", "〜する前に", "〜さえあれば"], answer: 1, explain: "whereas＝〜する一方で（対比を表す接続詞）。" },
          { type: "choice", q: "「declare」の意味は？", choices: ["〜を宣言する", "〜を拒否する", "〜を延期する", "〜を修理する"], answer: 0, explain: "declare O＝Oを宣言する。" },
          { type: "choice", q: "「definitely」の意味は？", choices: ["たぶん", "確実に・明確に", "まれに", "一時的に"], answer: 1, explain: "definitely＝確実に、明確に。" },
          { type: "choice", q: "「cope with A」の意味は？", choices: ["Aをうまく処理する", "Aを無視する", "Aを所有する", "Aを輸入する"], answer: 0, explain: "cope with A＝Aをうまく処理する、対処する。" },
          { type: "choice", q: "「contrary to A」の意味は？", choices: ["Aに加えて", "Aと反対の", "Aのおかげで", "Aの代わりに"], answer: 1, explain: "contrary to A＝Aと反対の。" },
          { type: "choice", q: "「distribute」の意味は？", choices: ["〜を集める", "〜を配付する・分配する", "〜を破棄する", "〜を発明する"], answer: 1, explain: "distribute O＝Oを配付する、分配する、流通させる。" },
          { type: "choice", q: "「secure」の意味は？", choices: ["〜を確保する・守る", "〜を危険にさらす", "〜を疑う", "〜を売る"], answer: 0, explain: "secure O＝Oを確保する、守る。形容詞では『安全な』。" },
          { type: "choice", q: "「interact with A」の意味は？", choices: ["Aを避ける", "Aと相互に作用する・交流する", "Aを支配する", "Aを観察する"], answer: 1, explain: "interact with A＝Aと相互に作用する、交流する。" },
          { type: "choice", q: "「determine」の意味として正しいものは？", choices: ["〜を決定する", "〜を忘れる", "〜を借りる", "〜を壊す"], answer: 0, explain: "determine O＝Oを決定する。be determined to V＝Vを決心している。" },
          { type: "input", q: "「succeed」には2つの意味がある。『成功する』ともう一つ、目的語をとる意味を日本語で書こう。", answers: ["〜の後を継ぐ", "後を継ぐ", "継承する", "跡を継ぐ", "継ぐ", "後を継ぐこと"], explain: "succeed O＝Oの後を継ぐ。succeed in 〜＝〜に成功する。" },
        ],
      },
    ],
  },
];

/* 学習の進め方モード（単元内の進み方） */
const STUDY_MODES = {
  detail: {
    label: "じっくり学習",
    icon: "🧱",
    desc: "診断 → 講義 → 演習 をフルで進める。理解の穴を残さず積み上げる王道ルート。",
  },
  quick: {
    label: "短期学習",
    icon: "⚡",
    desc: "講義は要点のみ、演習中心で高速周回。短期間で範囲を一気に広げる総復習ルート。",
  },
};

/* 習熟レベル定義（演習の正答率で判定） */
const MASTERY_LEVELS = [
  { key: "none", label: "未学習", min: -1, color: "#c2c8d0" },
  { key: "beginner", label: "初級", min: 0, color: "#e3a008" },
  { key: "intermediate", label: "中級", min: 50, color: "#3b82f6" },
  { key: "advanced", label: "上級", min: 75, color: "#8b5cf6" },
  { key: "passed", label: "合格", min: 100, color: "#16a34a" },
];

/* メダル定義（演習を全問正解した周回数で判定） */
const MEDALS = [
  { key: "shiny", label: "シャイニーメダル", emoji: "🌟", runs: 3 },
  { key: "gold", label: "金メダル", emoji: "🥇", runs: 2 },
  { key: "silver", label: "銀メダル", emoji: "🥈", runs: 1 },
];

/* 学習のコツ（英語学習の進め方ガイド） */
const STUDY_TIPS = {
  intro:
    "学習データや合格者の声から見えてきた、英語の伸ばし方のコツ。各単元の「診断 → 講義 → 演習」とあわせて活用しよう。",
  schedule: [
    "高3の夏までに、英単語・英文法を一通り学習し終えるのが目安。秋からは志望校対策に移る。",
    "毎日の優先順位は ①英単語 → ②英文法 → ③（必要なら）リスニング。少量でも毎日続けることを最優先に。",
    "語彙量の目安：中学で2,000〜2,500語、高校で4,000〜5,000語（難関大志望はさらに熟語1,000〜1,500語）。",
  ],
  sections: [
    {
      area: "英単語",
      icon: "📖",
      points: [
        "目標は「見て1秒で意味が出る」状態。眺めるだけでなく、意味を思い出す・書き出すアウトプット型で覚える。",
        "短時間で何度も思い出すサイクルを回す。復習間隔は『翌日 → 3日後 → 1週間後』と段階的に広げると長期記憶になる。",
        "見る・聞く・書く・話すの多角的接触。英→日／日→英の双方向で覚える。",
        "1日10〜15分でも毎日。時間と場所を決めて習慣化する。語源に着目すると初見語も推測できる。",
      ],
    },
    {
      area: "英文法",
      icon: "🧩",
      points: [
        "「インプット（覚える）→ アウトプット（解く）→ 振り返り（間違い直し）」を単元ごとに回す。",
        "順序は『英文法（語順ルール）』→『英文解釈（複雑な文の意味）』。完璧より「長文が読める程度」を目標に。",
        "模試やテストで読めなかった英文から復習する。間違いが減らなければ中学範囲まで戻る。",
      ],
    },
    {
      area: "長文読解",
      icon: "📰",
      points: [
        "英単語・英文法が7割以上定着してから本格化。「解答20分＋採点・振り返り20分＝40分」を1セットに。",
        "振り返りは「単語が分かるか → 文法が分かるか」の順に確認。まずは短文の構文解析から。",
        "文章タイプ（論説文／物語文）で読み方を変える。志望校の過去問で出題傾向をつかむ。",
        "ディスコースマーカー（however, because, as a result など）で文と文の論理関係をとらえる。",
      ],
    },
    {
      area: "リスニング",
      icon: "🎧",
      points: [
        "共通テストや一部の難関大で必要。シャドーイング（音声を追って発音）とディクテーション（書き起こし）が有効。",
        "毎日聴く習慣をつくる。聴き流さず、能動的に取り組むことが大切。",
      ],
    },
  ],
};
